/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Home interface for Leave.
 * @since Sep 26, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface LeaveHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Leave";
   public static final String JNDI_NAME="Leave";

   public com.gseo.zk.hr.Leave create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
