/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Local interface for Leave.
 * @since Sep 26, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface LeaveLocal
   extends javax.ejb.EJBLocalObject
{

}
