/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Local home interface for Leave.
 * @since Sep 26, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface LeaveLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LeaveLocal";
   public static final String JNDI_NAME="LeaveLocal";

   public com.gseo.zk.hr.LeaveLocal create()
      throws javax.ejb.CreateException;

}
