/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.ws;

/**
 * Local home interface for WebServiceClient.
 * @since Oct 1, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface WebServiceClientLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WebServiceClientLocal";
   public static final String JNDI_NAME="WebServiceClientLocal";

   public com.gseo.zk.ws.WebServiceClientLocal create()
      throws javax.ejb.CreateException;

}
