/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.ws;

/**
 * Remote interface for WebServiceClient.
 * @since Oct 1, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface WebServiceClient
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * Call Web service on outside server <!-- begin-xdoclet-definition -->
    * @generated 
    * @param address ex: "http://192.168.100.108/hrws/Integration.asmx"
    * @param soapAction ex: "http://dcms.com.cn/core/GeneralService/IntegrationByXmlWithLanguageEx"
    * @param method ex: "IntegrationByXmlWithLanguageEx"
    * @param params the pair data of key and value to send (becomes the content of SOAP body) <pre>{@code ex: Map params = new HashMap(); params.put("pXml", "<Request><Access></Access><RequestContent></RequestContent></Request>"); params.put("language", "1"); }</pre>
    * @return String Web service response XML information    */
   public java.lang.String callWebService( java.lang.String address,java.lang.String soapAction,java.lang.String method,java.util.Map params )
      throws java.rmi.RemoteException;

   /**
    * Call method "IntegrationByXmlWithLanguageEx" of "http://192.168.100.108/hrws/Integration.asmx" web service <!-- begin-xdoclet-definition -->
    * @generated 
    * @param xml the string of XML structure
    * @return String Web service response XML information    */
   public java.lang.String IntegrationByXmlWithLanguageEx( java.lang.String xml )
      throws java.rmi.RemoteException;

   /**
    * Call method "IntegrationByXmlWithLanguageEx" on specifying the address of the service <!-- begin-xdoclet-definition -->
    * @generated 
    * @param address ex: "http://192.168.100.108/hrws/Integration.asmx"
    * @param xml the string of XML structure
    * @return String Web service response XML information    */
   public java.lang.String IntegrationByXmlWithLanguageEx( java.lang.String address,java.lang.String xml )
      throws java.rmi.RemoteException;

   /**
    * Call method "IntegrationByXmlWithLanguageEx" on specifying the address of the service <!-- begin-xdoclet-definition -->
    * @generated 
    * @param address ex: "http://192.168.100.108/hrws/Integration.asmx"
    * @param xml the string of XML structure
    * @param language 0=Chinese Simplify; 1=Chinese Tradition; 2=English (always pass 1 if you have no idea)
    * @return String Web service response XML information    */
   public java.lang.String IntegrationByXmlWithLanguageEx( java.lang.String address,java.lang.String xml,java.lang.String language )
      throws java.rmi.RemoteException;

}
