/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.ws;

/**
 * Local interface for WebServiceClient.
 * @since Oct 1, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface WebServiceClientLocal
   extends javax.ejb.EJBLocalObject
{

}
