/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Local home interface for ForgotClockIn.
 * @generated 
 * @wtp generated
 */
public interface ForgotClockInLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ForgotClockInLocal";
   public static final String JNDI_NAME="ForgotClockInLocal";

   public com.gseo.zk.hr.ForgotClockInLocal create()
      throws javax.ejb.CreateException;

}
