/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Home interface for ForgotClockIn.
 * @generated 
 * @wtp generated
 */
public interface ForgotClockInHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ForgotClockIn";
   public static final String JNDI_NAME="ForgotClockIn";

   public com.gseo.zk.hr.ForgotClockIn create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
