/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Remote interface for ForgotClockIn.
 * @generated 
 * @wtp generated
 */
public interface ForgotClockIn
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * Check and Remove from AttendanceCollect Table via AttendanceCollectId <!-- begin-xdoclet-definition -->
    * @generated 
    * @param pDataSource ex:"HRMDS"
    * @param collectId collect id
    * @return String 0 means OK else the info with error message    */
   public java.lang.String checktoRemoveAttendanceCollectData( java.lang.String pDataSource,java.lang.String collectId )
      throws java.rmi.RemoteException;

   /**
    * Only for saveForESS that can not provide the serial key to call Web service <!-- begin-xdoclet-definition -->
    * @generated 
    * @param address ex: "http://192.168.100.108/hrws/Integration.asmx"
    * @param pDataSource ex:"NaNaDS"
    * @param serialNumber
    * @return String 0 means OK else the info with error message    */
   public java.lang.String saveForESS( java.lang.String address,java.lang.String pDataSource,java.lang.String serialNumber )
      throws java.rmi.RemoteException;

}
