/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Local interface for GoBusinessTrip.
 * @generated 
 * @wtp generated
 */
public interface GoBusinessTripLocal
   extends javax.ejb.EJBLocalObject
{

}
