/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Local home interface for GoBusinessTrip.
 * @generated 
 * @wtp generated
 */
public interface GoBusinessTripLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GoBusinessTripLocal";
   public static final String JNDI_NAME="GoBusinessTripLocal";

   public com.gseo.zk.hr.GoBusinessTripLocal create()
      throws javax.ejb.CreateException;

}
