/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Home interface for GoBusinessTrip.
 * @generated 
 * @wtp generated
 */
public interface GoBusinessTripHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GoBusinessTrip";
   public static final String JNDI_NAME="GoBusinessTrip";

   public com.gseo.zk.hr.GoBusinessTrip create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
