/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.hr;

/**
 * Remote interface for GoBusinessTrip.
 * @generated 
 * @wtp generated
 */
public interface GoBusinessTrip
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * Only for auditForESS that can not provide the serial key to call Web service <!-- begin-xdoclet-definition -->
    * @generated 
    * @param address ex: "http://192.168.100.108/hrws/Integration.asmx"
    * @param pDataSource ex:"HRMDS"
    * @param pFormInstance tag of 'txtSerialNumber' and 'txtEmpid'
    * @return String 0 means OK else the info with error message    */
   public java.lang.String auditForESS( java.lang.String address,java.lang.String pDataSource,com.dsc.nana.domain.form.FormInstance pFormInstance )
      throws java.rmi.RemoteException;

   /**
    * Only for auditForESS that can not provide the serial key to call Web service <!-- begin-xdoclet-definition -->
    * @generated 
    * @param address ex: "http://192.168.100.108/hrws/Integration.asmx"
    * @param pDataSource ex:"HRMDS"
    * @param serialNumber
    * @param empId
    * @return String 0 means OK else the info with error message    */
   public java.lang.String auditForESS( java.lang.String address,java.lang.String pDataSource,java.lang.String serialNumber,java.lang.String empId )
      throws java.rmi.RemoteException;

}
