/*
 * Generated by XDoclet - Do not edit!
 */
package com.gseo.zk.ws;

/**
 * Home interface for WebServiceClient.
 * @since Oct 1, 2014 <!-- end-user-doc --> <!-- begin-xdoclet-definition -->
 * @generated 
 * @wtp generated
 */
public interface WebServiceClientHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WebServiceClient";
   public static final String JNDI_NAME="WebServiceClient";

   public com.gseo.zk.ws.WebServiceClient create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
